language:   node_js

branches:
  only:
    - master

node_js:
    - "14"
    - "15"

install:
    - npm i

script:
    - npm test
    - npm run lint
    - npm run build -- --env API=mock --mode=production
    - npm run build -- --env API=ws --mode=production
