language:   node_js

node_js:
    - "8"
    - "9"
    - "10"
    - "11"

install:
    - npm i

env:
    - NODE_ENV=prod

script:
    - npm test
    - npm run lint
    - API=mock npm run build
    - API=ws npm run build
